//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMM.Projects.Apresentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batidas
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int funcionario_id { get; set; }
        public string entrada1 { get; set; }
        public string saida1 { get; set; }
        public string entrada2 { get; set; }
        public string saida2 { get; set; }
        public string entrada3 { get; set; }
        public string saida3 { get; set; }
        public string entrada4 { get; set; }
        public string saida4 { get; set; }
        public string entrada5 { get; set; }
        public string saida5 { get; set; }
        public string ajuste { get; set; }
        public string abono2 { get; set; }
        public string abono3 { get; set; }
        public string abono4 { get; set; }
        public bool reserva_refeicao { get; set; }
        public string obs { get; set; }
        public string mem_entrada1 { get; set; }
        public string mem_saida1 { get; set; }
        public string mem_entrada2 { get; set; }
        public string mem_saida2 { get; set; }
        public string mem_entrada3 { get; set; }
        public string mem_saida3 { get; set; }
        public string mem_entrada4 { get; set; }
        public string mem_saida4 { get; set; }
        public string mem_entrada5 { get; set; }
        public string mem_saida5 { get; set; }
        public bool auto_entrada1 { get; set; }
        public bool auto_saida1 { get; set; }
        public bool auto_entrada2 { get; set; }
        public bool auto_saida2 { get; set; }
        public bool auto_entrada3 { get; set; }
        public bool auto_saida3 { get; set; }
        public bool auto_entrada4 { get; set; }
        public bool auto_saida4 { get; set; }
        public bool auto_entrada5 { get; set; }
        public bool auto_saida5 { get; set; }
        public bool compensado { get; set; }
        public bool almoco_livre { get; set; }
        public bool neutro { get; set; }
        public bool nbanco { get; set; }
        public Nullable<byte> t_extra { get; set; }
        public Nullable<byte> t_falta { get; set; }
        public string bac_entrada1 { get; set; }
        public string bac_saida1 { get; set; }
        public string bac_entrada2 { get; set; }
        public string bac_saida2 { get; set; }
        public string bac_entrada3 { get; set; }
        public string bac_saida3 { get; set; }
        public string bac_entrada4 { get; set; }
        public string bac_saida4 { get; set; }
        public string bac_entrada5 { get; set; }
        public string bac_saida5 { get; set; }
        public string acrescimo { get; set; }
        public bool somar_t { get; set; }
        public Nullable<int> horario_num { get; set; }
        public Nullable<int> equip_entrada1 { get; set; }
        public Nullable<int> equip_saida1 { get; set; }
        public Nullable<int> equip_entrada2 { get; set; }
        public Nullable<int> equip_saida2 { get; set; }
        public Nullable<int> equip_entrada3 { get; set; }
        public Nullable<int> equip_saida3 { get; set; }
        public Nullable<int> equip_entrada4 { get; set; }
        public Nullable<int> equip_saida4 { get; set; }
        public Nullable<int> equip_entrada5 { get; set; }
        public Nullable<int> equip_saida5 { get; set; }
        public Nullable<int> extra_especial_id { get; set; }
        public bool folga { get; set; }
        public Nullable<int> fdados_entrada1 { get; set; }
        public Nullable<int> fdados_saida1 { get; set; }
        public Nullable<int> fdados_entrada2 { get; set; }
        public Nullable<int> fdados_saida2 { get; set; }
        public Nullable<int> fdados_entrada3 { get; set; }
        public Nullable<int> fdados_saida3 { get; set; }
        public Nullable<int> fdados_entrada4 { get; set; }
        public Nullable<int> fdados_saida4 { get; set; }
        public Nullable<int> fdados_entrada5 { get; set; }
        public Nullable<int> fdados_saida5 { get; set; }
        public bool dsr_especial { get; set; }
    
        public virtual funcionarios funcionarios { get; set; }
    }
}
