//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMM.Projects.Apresentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public funcionarios()
        {
            this.batidas = new HashSet<batidas>();
        }
    
        public int id { get; set; }
        public string n_folha { get; set; }
        public string nome { get; set; }
        public string n_identificador { get; set; }
        public string carteira { get; set; }
        public Nullable<int> empresa_id { get; set; }
        public Nullable<int> horario_num { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> funcao_id { get; set; }
        public Nullable<int> departamento_id { get; set; }
        public Nullable<System.DateTime> admissao { get; set; }
        public Nullable<System.DateTime> demissao { get; set; }
        public bool nao_digital { get; set; }
        public Nullable<System.DateTime> afast_data_ini { get; set; }
        public Nullable<System.DateTime> afast_data_fim { get; set; }
        public string afast_motivo { get; set; }
        public Nullable<int> afast_justificativa_id { get; set; }
        public bool invisivel { get; set; }
        public Nullable<int> escala_id { get; set; }
        public bool escala_mensal { get; set; }
        public string t_horario { get; set; }
        public Nullable<int> senha_equipamento { get; set; }
        public Nullable<int> filtro1_id { get; set; }
        public Nullable<int> filtro2_id { get; set; }
        public string obs { get; set; }
        public string xcampo1 { get; set; }
        public Nullable<int> alt2_horario_num { get; set; }
        public Nullable<int> alt3_horario_num { get; set; }
        public Nullable<int> alt4_horario_num { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string cep { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string rg { get; set; }
        public Nullable<System.DateTime> expedicao { get; set; }
        public string ssp { get; set; }
        public string cpf { get; set; }
        public string mae { get; set; }
        public string pai { get; set; }
        public Nullable<System.DateTime> nascimento { get; set; }
        public bool sexo_masculino { get; set; }
        public Nullable<int> estado_civil_id { get; set; }
        public string nacionalidade { get; set; }
        public string naturalidade { get; set; }
        public string web_senha { get; set; }
        public bool web_nao_altera { get; set; }
        public bool web_bloqueado { get; set; }
        public Nullable<int> alt_usuario_id { get; set; }
        public Nullable<System.DateTime> alt_data { get; set; }
        public bool master { get; set; }
        public string n_provisorio { get; set; }
        public Nullable<System.DateTime> provisorio_data_ini { get; set; }
        public Nullable<System.DateTime> provisorio_data_fim { get; set; }
        public Nullable<int> cidade_empresa_id { get; set; }
        public Nullable<int> estrutura_id { get; set; }
        public string assinatura_eletronica { get; set; }
        public Nullable<int> integracao_id { get; set; }
        public Nullable<System.DateTime> bh_inicio { get; set; }
        public string centro_custos { get; set; }
        public Nullable<int> nivel_id { get; set; }
        public bool web_auto_aceitar { get; set; }
        public string n_pis { get; set; }
        public bool web_solicitacoes { get; set; }
        public Nullable<System.DateTime> data_alteracao_portaria { get; set; }
        public Nullable<System.DateTime> web_data_fechamento { get; set; }
        public Nullable<short> especial_insight_sinha { get; set; }
        public Nullable<int> motivo_demissao_id { get; set; }
        public bool web_somente_visto { get; set; }
        public bool web_nao_incluir_manual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batidas> batidas { get; set; }
    }
}
