
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_beneficio
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_beneficio()
    {

        this.ap_beneficioxvinculo = new HashSet<ap_beneficioxvinculo>();

    }


    public int BNF_ID { get; set; }

    public string BNF_DESCRICAO { get; set; }

    public Nullable<decimal> BNF_VALOR { get; set; }

    public Nullable<System.DateTime> BNF_REGDATE { get; set; }

    public Nullable<int> BNF_REGUSER { get; set; }

    public string BNF_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_beneficioxvinculo> ap_beneficioxvinculo { get; set; }

}

}
