
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_banco
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_banco()
    {

        this.ap_funcionario = new HashSet<ap_funcionario>();

    }


    public int BNC_ID { get; set; }

    public string BNC_DESCRICAO { get; set; }

    public string BNC_STATUS { get; set; }

    public Nullable<System.DateTime> BNC_REGDATE { get; set; }

    public Nullable<int> BNC_REGUSER { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcionario> ap_funcionario { get; set; }

}

}
