
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_conselho
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_conselho()
    {

        this.ap_conselhoclasse = new HashSet<ap_conselhoclasse>();

    }


    public int CON_ID { get; set; }

    public Nullable<int> CRG_ID { get; set; }

    public string CON_NOME { get; set; }

    public Nullable<System.DateTime> CON_REGDATE { get; set; }

    public Nullable<int> CON_REGUSER { get; set; }

    public string CON_STATUS { get; set; }



    public virtual ap_cargo ap_cargo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_conselhoclasse> ap_conselhoclasse { get; set; }

}

}
