
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_controlecnh
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_controlecnh()
    {

        this.ap_controlecnh_aux = new HashSet<ap_controlecnh_aux>();

    }


    public int CNH_ID { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public string CNH_NREG { get; set; }

    public Nullable<System.DateTime> CNH_REGDATE { get; set; }

    public Nullable<int> CNH_REGUSER { get; set; }

    public string CNH_STATUS { get; set; }



    public virtual ap_vinculo ap_vinculo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_controlecnh_aux> ap_controlecnh_aux { get; set; }

}

}
