
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_cid10
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_cid10()
    {

        this.pon_justificativaponto = new HashSet<pon_justificativaponto>();

    }


    public int CID_ID { get; set; }

    public string CID_CODIGO { get; set; }

    public string CID_DESCRICAO { get; set; }

    public Nullable<System.DateTime> CID_REGDATE { get; set; }

    public Nullable<int> CID_REGUSER { get; set; }

    public string CID_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<pon_justificativaponto> pon_justificativaponto { get; set; }

}

}
