
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_curso
{

    public int CRS_ID { get; set; }

    public string CRS_NOME { get; set; }

    public Nullable<int> CONCLA_ID { get; set; }

    public string CRS_ORGAOEMISSOR { get; set; }

    public Nullable<System.DateTime> CRS_REGDATE { get; set; }

    public Nullable<int> CRS_REGUSER { get; set; }

    public string CRS_STATUS { get; set; }



    public virtual ap_conselhoclasse ap_conselhoclasse { get; set; }

}

}
