
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_cessao
{

    public int CSS_ID { get; set; }

    public Nullable<int> FUN_ID { get; set; }

    public string CSS_ORGAO_ORIGEM { get; set; }

    public string CSS_ORGAO_DESTINO { get; set; }

    public Nullable<int> CSS_ONUSORIGEM { get; set; }

    public Nullable<System.DateTime> CSS_DATA { get; set; }

    public Nullable<System.DateTime> CSS_REGDATE { get; set; }

    public Nullable<int> CSS_REGUSER { get; set; }

    public string CSS_STATUS { get; set; }



    public virtual ap_funcionario ap_funcionario { get; set; }

}

}
