
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_conselhoclasse
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_conselhoclasse()
    {

        this.ap_curso = new HashSet<ap_curso>();

    }


    public int CONCLA_ID { get; set; }

    public Nullable<System.DateTime> CONCLA_DATAQUITACAO { get; set; }

    public string CONCLA_REFANO { get; set; }

    public Nullable<System.DateTime> CONCLA_REGDATE { get; set; }

    public Nullable<int> CONCLA_REGUSER { get; set; }

    public string CONCLA_STATUS { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public Nullable<int> CON_ID { get; set; }

    public Nullable<System.DateTime> CONCLA_DATARECEBIMENTO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_curso> ap_curso { get; set; }

    public virtual ap_vinculo ap_vinculo { get; set; }

    public virtual ap_conselho ap_conselho { get; set; }

}

}
