
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_feriado
{

    public int FER_ID { get; set; }

    public string FER_DESCRICAO { get; set; }

    public int FER_TIPO { get; set; }

    public Nullable<System.DateTime> FER_DATA { get; set; }

    public int FER_REGUSER { get; set; }

    public System.DateTime FER_REGDATE { get; set; }

    public string FER_STATUS { get; set; }

}

}
