
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_funcionario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_funcionario()
    {

        this.ap_cartaosaude = new HashSet<ap_cartaosaude>();

        this.ap_cessao = new HashSet<ap_cessao>();

        this.ap_funcionarioxcurso = new HashSet<ap_funcionarioxcurso>();

        this.ap_funcionarioxdependente = new HashSet<ap_funcionarioxdependente>();

        this.ap_funcionarioxfoto = new HashSet<ap_funcionarioxfoto>();

        this.ap_vinculo = new HashSet<ap_vinculo>();

        this.sass_consulta = new HashSet<sass_consulta>();

    }


    public int FUN_ID { get; set; }

    public string FUN_MATRICULA { get; set; }

    public string FUN_NOME { get; set; }

    public string FUN_NOMECRACHA { get; set; }

    public string FUN_SEXO { get; set; }

    public Nullable<int> BNC_ID { get; set; }

    public string FUN_AGENCIA { get; set; }

    public string FUN_CONTACORRENTE { get; set; }

    public Nullable<int> FUN_ESTADOCIVIL { get; set; }

    public string FUN_CONJUGE { get; set; }

    public string FUN_NOMEPAI { get; set; }

    public string FUN_NOMEMAE { get; set; }

    public Nullable<int> FUN_TIPOSANGUINEO { get; set; }

    public string FUN_LOGRADOURO { get; set; }

    public string FUN_ENDERECO { get; set; }

    public string FUN_NUMEROEND { get; set; }

    public string FUN_BAIRRO { get; set; }

    public string FUN_COMPLEMENTO { get; set; }

    public string FUN_CEP { get; set; }

    public string FUN_CIDADE { get; set; }

    public string FUN_CIDADENATAL { get; set; }

    public Nullable<System.DateTime> FUN_DATANASCIMENTO { get; set; }

    public string FUN_NACIONALIDADE { get; set; }

    public string FUN_RG { get; set; }

    public string FUN_RGEMISSOR { get; set; }

    public string FUN_RGESTADO { get; set; }

    public Nullable<System.DateTime> FUN_RGDATAEMISSAO { get; set; }

    public string FUN_CPF { get; set; }

    public string FUN_PIS { get; set; }

    public string FUN_TITULOELEITOR { get; set; }

    public string FUN_TITULOZONA { get; set; }

    public string FUN_TITULOSESSAO { get; set; }

    public Nullable<System.DateTime> FUN_TITULODATAEMISSAO { get; set; }

    public string FUN_CERTIFICADOMILITAR { get; set; }

    public string FUN_CMSERIE { get; set; }

    public string FUN_CMCORPORACAO { get; set; }

    public string FUN_CTPS { get; set; }

    public Nullable<System.DateTime> FUN_CTPSDATAEMISSAO { get; set; }

    public Nullable<System.DateTime> FUN_CNHVALIDADE { get; set; }

    public string FUN_CNH { get; set; }

    public string FUN_CNHCATEGORIA { get; set; }

    public string FUN_EMAIL { get; set; }

    public string FUN_TELEFONE { get; set; }

    public string FUN_CELULAR { get; set; }

    public Nullable<int> FUN_ESCOLARIDADE { get; set; }

    public string FUN_IDIOMA { get; set; }

    public Nullable<int> FUN_NECESSIDADE_ESPECIAL { get; set; }

    public string FUN_ASSISTENCIAMEDICA { get; set; }

    public Nullable<int> FUN_IMOVEL { get; set; }

    public string FUN_OBSERVACAO { get; set; }

    public Nullable<System.DateTime> FUN_REGDATE { get; set; }

    public Nullable<int> FUN_REGUSER { get; set; }

    public string FUN_STATUS { get; set; }

    public string FUN_CNS { get; set; }



    public virtual ap_banco ap_banco { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_cartaosaude> ap_cartaosaude { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_cessao> ap_cessao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcionarioxcurso> ap_funcionarioxcurso { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcionarioxdependente> ap_funcionarioxdependente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcionarioxfoto> ap_funcionarioxfoto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_vinculo> ap_vinculo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<sass_consulta> sass_consulta { get; set; }

}

}
