
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_funcionariocracha
{

    public int FUNCRC_ID { get; set; }

    public string FUNCRC_NUMERO { get; set; }

    public Nullable<System.DateTime> FUNCRC_DATAEMISSAO { get; set; }

    public Nullable<int> FUNCRC_TIPO { get; set; }

    public Nullable<System.DateTime> FUNCRC_DATASOLICITACAO { get; set; }

    public Nullable<int> FUNCRC_SITUACAO { get; set; }

    public string FUNCRC_OBSERVACAO { get; set; }

    public Nullable<System.DateTime> FUNCRC_REGDATE { get; set; }

    public Nullable<int> FUNCRC_REGUSER { get; set; }

    public string FUNCRC_STATUS { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public Nullable<int> FUNCRC_RESPSOLICITACAO { get; set; }

    public Nullable<int> FUNCRC_RESPEMISSAO { get; set; }



    public virtual ap_vinculo ap_vinculo { get; set; }

}

}
