
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_funcionarioxdependente
{

    public int FUNDEP_ID { get; set; }

    public Nullable<int> FUN_ID { get; set; }

    public string FUNDEP_NOME { get; set; }

    public Nullable<int> FUNDEP_TIPO { get; set; }

    public string FUNDEP_CPF { get; set; }

    public Nullable<System.DateTime> FUNDEP_DATANASCIMENTO { get; set; }

    public Nullable<System.DateTime> FUNDEP_REGDATE { get; set; }

    public Nullable<int> FUNDEP_REGUSER { get; set; }

    public string FUNDEP_STATUS { get; set; }



    public virtual ap_funcionario ap_funcionario { get; set; }

}

}
