
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_funcaoxvinculo
{

    public int FNCVNC_ID { get; set; }

    public Nullable<int> FNC_ID { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public Nullable<System.DateTime> FNCVNC_DATAINICIO { get; set; }

    public Nullable<System.DateTime> FNCVNC_DATAFIM { get; set; }

    public Nullable<System.DateTime> FNCVNC_REGDATE { get; set; }

    public Nullable<int> FNCVNC_REGUSER { get; set; }

    public string FNCVNC_STATUS { get; set; }

    public string FNCVNC_NUMPORTARIA { get; set; }

    public Nullable<System.DateTime> FNCVNC_DATAPORTARIA { get; set; }



    public virtual ap_funcao ap_funcao { get; set; }

    public virtual ap_vinculo ap_vinculo { get; set; }

}

}
