
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_funcao
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_funcao()
    {

        this.ap_funcaoxvinculo = new HashSet<ap_funcaoxvinculo>();

    }


    public int FNC_ID { get; set; }

    public string FNC_NOME { get; set; }

    public Nullable<int> FNC_VENCIMENTO { get; set; }

    public Nullable<int> REFFNC_ID { get; set; }

    public Nullable<System.DateTime> FNC_REGDATE { get; set; }

    public Nullable<int> FNC_REGUSER { get; set; }

    public string FNC_STATUS { get; set; }

    public Nullable<int> FNC_QUANTIDADE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcaoxvinculo> ap_funcaoxvinculo { get; set; }

    public virtual ap_referenciafuncao ap_referenciafuncao { get; set; }

}

}
