
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_ferias
{

    public int FRS_ID { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public Nullable<System.DateTime> FRS_DATA_INICIOAQUISITIVO { get; set; }

    public Nullable<System.DateTime> FRS_DATA_FIMAQUISITIVO { get; set; }

    public Nullable<System.DateTime> FRS_DATA_INICIOGOZO { get; set; }

    public Nullable<System.DateTime> FRS_DATA_RETORNO { get; set; }

    public Nullable<System.DateTime> FRS_REGDATE { get; set; }

    public Nullable<int> FRS_REGUSER { get; set; }

    public string FRS_STATUS { get; set; }

    public string FRS_NUMPORTARIA { get; set; }

    public Nullable<System.DateTime> FRS_DATAPORTARIA { get; set; }

    public string FRS_OBSERVACAO { get; set; }

    public Nullable<System.DateTime> FRS_DATA_FIMGOZO { get; set; }



    public virtual ap_vinculo ap_vinculo { get; set; }

}

}
