
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_horarioxdiasemana
{

    public int HORDSEM_ID { get; set; }

    public Nullable<int> HOR_ID { get; set; }

    public Nullable<int> HORDSEM_DIA { get; set; }

    public Nullable<System.TimeSpan> HORDSEM_ENTRADA { get; set; }

    public Nullable<System.TimeSpan> HORDSEM_SAIDA { get; set; }

    public Nullable<int> HORDSEM_REGUSER { get; set; }

    public Nullable<System.DateTime> HORDSEM_REGDATE { get; set; }

    public string HORDSEM_STATUS { get; set; }

}

}
