
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_horario
{

    public int HOR_ID { get; set; }

    public string HOR_DESCRICAO { get; set; }

    public Nullable<System.TimeSpan> HOR_TOLERANCIA { get; set; }

    public Nullable<int> HOR_REGUSER { get; set; }

    public Nullable<System.DateTime> HOR_REGDATE { get; set; }

    public string HOR_STATUS { get; set; }

}

}
