
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_licencapericia
{

    public int LICPRC_ID { get; set; }

    public Nullable<int> LIC_ID { get; set; }

    public Nullable<int> STPRC_ID { get; set; }

    public string LICPRC_SENHA { get; set; }

    public Nullable<System.DateTime> LICPRC_DATAHORA { get; set; }

    public Nullable<System.DateTime> LICPRC_DATAAGENDAMENTO { get; set; }

    public Nullable<System.DateTime> LICPRC_RETORNO { get; set; }

    public string LICPRC_NOMEARQUIVO { get; set; }

    public byte[] LICPRC_ARQUIVO { get; set; }

    public Nullable<int> LICPRC_REGUSER { get; set; }

    public Nullable<System.DateTime> LICPRC_REGDATE { get; set; }

    public string LICPRC_STATUS { get; set; }



    public virtual ap_licenca ap_licenca { get; set; }

    public virtual ap_licencasituacaopericia ap_licencasituacaopericia { get; set; }

}

}
