
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_licencapericiasituacao
{

    public int PRCST_ID { get; set; }

    public string PRCST_NOME { get; set; }

    public Nullable<System.DateTime> PRCST_REGDATE { get; set; }

    public Nullable<int> PRCST_REGUSER { get; set; }

    public string PRCST_STATUS { get; set; }

}

}
