
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_referenciafuncao
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_referenciafuncao()
    {

        this.ap_funcao = new HashSet<ap_funcao>();

    }


    public int REFFNC_ID { get; set; }

    public string REFFNC_NOME { get; set; }

    public Nullable<double> REFFNC_VALOR { get; set; }

    public string REFFNC_OBSERVACAO { get; set; }

    public Nullable<System.DateTime> REFFNC_REGDATE { get; set; }

    public Nullable<int> REFFNC_REGUSER { get; set; }

    public string REFFNC_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcao> ap_funcao { get; set; }

}

}
