
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_unidade
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_unidade()
    {

        this.ap_unidade1 = new HashSet<ap_unidade>();

        this.ap_vinculoxunidade = new HashSet<ap_vinculoxunidade>();

    }


    public int UND_ID { get; set; }

    public string UND_CODIGO { get; set; }

    public string UND_NOME { get; set; }

    public string UND_SIGLA { get; set; }

    public Nullable<System.DateTime> UND_DATAINICIO { get; set; }

    public Nullable<System.DateTime> UND_DATAFIM { get; set; }

    public string UND_DIRETORIO { get; set; }

    public Nullable<int> UND_NIVEL { get; set; }

    public Nullable<int> UND_PAI { get; set; }

    public string UND_HISTORICO { get; set; }

    public string UND_RAMAL { get; set; }

    public string UND_COMPETENCIA { get; set; }

    public Nullable<System.DateTime> UND_REGDATE { get; set; }

    public Nullable<int> UND_REGUSER { get; set; }

    public string UND_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_unidade> ap_unidade1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_vinculoxunidade> ap_vinculoxunidade { get; set; }

}

}
