
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_vinculosituacao
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_vinculosituacao()
    {

        this.ap_vinculo = new HashSet<ap_vinculo>();

    }


    public int VNCST_ID { get; set; }

    public string VNCST_DESCRICAO { get; set; }

    public Nullable<int> VNCST_REGUSER { get; set; }

    public Nullable<System.DateTime> VNCST_REGDATE { get; set; }

    public string VNCST_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_vinculo> ap_vinculo { get; set; }

}

}
