
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_vinculoxunidade
{

    public int VNCU_ID { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public Nullable<int> UND_ID { get; set; }

    public string VNCU_ATRIBUICAO { get; set; }

    public Nullable<System.DateTime> VNCU_DATAINICIO { get; set; }

    public Nullable<System.DateTime> VNCU_DATAFIM { get; set; }

    public Nullable<System.DateTime> VNCU_REGDATE { get; set; }

    public Nullable<int> VNCU_REGUSER { get; set; }

    public string VNCU_STATUS { get; set; }



    public virtual ap_unidade ap_unidade { get; set; }

    public virtual ap_vinculo ap_vinculo { get; set; }

}

}
