
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ap_vinculo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ap_vinculo()
    {

        this.ap_beneficioxvinculo = new HashSet<ap_beneficioxvinculo>();

        this.ap_ferias = new HashSet<ap_ferias>();

        this.ap_funcaoxvinculo = new HashSet<ap_funcaoxvinculo>();

        this.ap_licenca = new HashSet<ap_licenca>();

        this.pon_horarioxvinculo = new HashSet<pon_horarioxvinculo>();

        this.pon_justificativaponto = new HashSet<pon_justificativaponto>();

        this.ap_vinculoxunidade = new HashSet<ap_vinculoxunidade>();

        this.ap_funcionariocracha = new HashSet<ap_funcionariocracha>();

        this.ap_conselhoclasse = new HashSet<ap_conselhoclasse>();

        this.sass_prontuario = new HashSet<sass_prontuario>();

        this.ap_controlecnh = new HashSet<ap_controlecnh>();

    }


    public int VNC_ID { get; set; }

    public Nullable<int> FUN_ID { get; set; }

    public Nullable<int> VNCTP_ID { get; set; }

    public Nullable<int> VNCST_ID { get; set; }

    public Nullable<int> CRG_ID { get; set; }

    public Nullable<System.DateTime> VNC_ADMISSAO { get; set; }

    public Nullable<System.DateTime> VNC_DEMISSAO { get; set; }

    public Nullable<int> VNC_AREA { get; set; }

    public string VNC_CONCURSO { get; set; }

    public string VNC_HISTORICO { get; set; }

    public Nullable<int> VNC_CARGAHORARIA { get; set; }

    public string VNC_ORGAO_ORIGEM { get; set; }

    public Nullable<System.DateTime> VNC_DATACESSAO { get; set; }

    public Nullable<System.DateTime> VNC_ENTRADA_APOSENT { get; set; }

    public Nullable<int> VNC_TIPO_APOSENT { get; set; }

    public string VNC_ONUS { get; set; }

    public Nullable<System.DateTime> VNC_REGDATE { get; set; }

    public Nullable<int> VNC_REGUSER { get; set; }

    public string VNC_STATUS { get; set; }

    public string VNC_ORGAO_DESTINO { get; set; }

    public Nullable<int> VNC_QTD { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_beneficioxvinculo> ap_beneficioxvinculo { get; set; }

    public virtual ap_cargo ap_cargo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_ferias> ap_ferias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcaoxvinculo> ap_funcaoxvinculo { get; set; }

    public virtual ap_funcionario ap_funcionario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_licenca> ap_licenca { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<pon_horarioxvinculo> pon_horarioxvinculo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<pon_justificativaponto> pon_justificativaponto { get; set; }

    public virtual ap_vinculosituacao ap_vinculosituacao { get; set; }

    public virtual ap_vinculotipo ap_vinculotipo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_vinculoxunidade> ap_vinculoxunidade { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_funcionariocracha> ap_funcionariocracha { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_conselhoclasse> ap_conselhoclasse { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<sass_prontuario> sass_prontuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ap_controlecnh> ap_controlecnh { get; set; }

}

}
