
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class pon_motivojustificativa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public pon_motivojustificativa()
    {

        this.pon_justificativaponto = new HashSet<pon_justificativaponto>();

    }


    public int MTVJUS_ID { get; set; }

    public string MTVJUS_NOME { get; set; }

    public Nullable<System.DateTime> MTVJUS_REGDATE { get; set; }

    public Nullable<int> MTVJUS_REGUSER { get; set; }

    public string MTVJUS_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<pon_justificativaponto> pon_justificativaponto { get; set; }

}

}
