
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class pon_situacaopericia
{

    public int STPRC_ID { get; set; }

    public string STPRC_NOME { get; set; }

    public Nullable<System.DateTime> STPRC_REGDATE { get; set; }

    public Nullable<int> STPRC_REGUSER { get; set; }

    public string STPRC_STATUS { get; set; }

}

}
