
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class pon_ponto
{

    public int PON_ID { get; set; }

    public Nullable<int> FUN_ID { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public string PON_VALIDATE { get; set; }

    public Nullable<int> PONIMP_ID { get; set; }

    public Nullable<System.DateTime> PON_DATA { get; set; }

    public string PON_ENTRADA1 { get; set; }

    public string PON_SAIDA1 { get; set; }

    public string PON_ENTRADA2 { get; set; }

    public string PON_SAIDA2 { get; set; }

    public string FUN_PIS { get; set; }

    public string FUN_MATRICULA { get; set; }



    public virtual pon_pontoimportacao pon_pontoimportacao { get; set; }

}

}
