
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class pon_justificativaponto
{

    public int JUSPT_ID { get; set; }

    public Nullable<int> MTVJUS_ID { get; set; }

    public Nullable<System.DateTime> JUSPT_DATAINICIO { get; set; }

    public Nullable<System.DateTime> JUSPT_DATAFIM { get; set; }

    public Nullable<System.DateTime> JUSPT_DATARECEBIMENTO { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public string JUSPT_OBSERVACAO { get; set; }

    public Nullable<System.DateTime> JUSPT_REGDATE { get; set; }

    public Nullable<int> JUSPT_REGUSER { get; set; }

    public string JUSPT_STATUS { get; set; }

    public Nullable<int> CID_ID { get; set; }



    public virtual ap_vinculo ap_vinculo { get; set; }

    public virtual pon_motivojustificativa pon_motivojustificativa { get; set; }

    public virtual ap_cid10 ap_cid10 { get; set; }

}

}
