
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class pon_pontoequipamento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public pon_pontoequipamento()
    {

        this.pon_pontoimportacao = new HashSet<pon_pontoimportacao>();

    }


    public int PONEQP_ID { get; set; }

    public string PONEQP_NOME { get; set; }

    public Nullable<System.DateTime> PONEQP_REGDATE { get; set; }

    public Nullable<int> PONEQP_REGUSER { get; set; }

    public string PONEQP_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<pon_pontoimportacao> pon_pontoimportacao { get; set; }

}

}
