
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class pon_horarioxvinculo
{

    public int HORVNC_ID { get; set; }

    public Nullable<int> HOR_ID { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public Nullable<System.DateTime> HORVNC_DATAINICIO { get; set; }

    public Nullable<System.DateTime> HORVNC_DATAFIM { get; set; }

    public Nullable<System.DateTime> HORVNC_REGDATE { get; set; }

    public Nullable<int> HORVNC_REGUSER { get; set; }

    public string HORVNC_STATUS { get; set; }



    public virtual ap_vinculo ap_vinculo { get; set; }

    public virtual pon_horario pon_horario { get; set; }

}

}
