
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class roles
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public roles()
    {

        this.systemuserxroles = new HashSet<systemuserxroles>();

    }


    public int ROL_ID { get; set; }

    public string ROL_NOME { get; set; }

    public Nullable<System.DateTime> ROL_REGDATE { get; set; }

    public Nullable<int> ROL_REGUSER { get; set; }

    public string ROL_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<systemuserxroles> systemuserxroles { get; set; }

}

}
