
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class sass_prontuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public sass_prontuario()
    {

        this.sass_prontuarioxavaliacao = new HashSet<sass_prontuarioxavaliacao>();

    }


    public int PRT_ID { get; set; }

    public Nullable<int> VNC_ID { get; set; }

    public Nullable<int> PRT_ACIDENTETRAB { get; set; }

    public string PRT_ACIDENTETRAB_DESCRICAO { get; set; }

    public Nullable<System.DateTime> PRT_DATAINICIO { get; set; }

    public Nullable<System.DateTime> PRT_DATAFIM { get; set; }

    public string PRT_ESCREVE { get; set; }

    public string PRT_CARTEIRATRAB_ATIVIDADES { get; set; }

    public Nullable<int> PRT_RUIDO { get; set; }

    public string PRT_RUIDO_TEMPO { get; set; }

    public string PRT_RUIDO_TIPO { get; set; }

    public Nullable<int> PRT_EXAMEAUDIOMETRICO_QTD { get; set; }

    public string PRT_EXAMEAUDIOMETRICO_EMPRESA { get; set; }

    public string PRT_ANTECEDENTEFAMILIAR { get; set; }

    public string PRT_ANTECEDENTEPESSOAL { get; set; }

    public Nullable<int> PRT_FILHO { get; set; }

    public string PRT_FILHO_TIPO { get; set; }

    public Nullable<int> PRT_REPCADASTRO { get; set; }

    public Nullable<int> PRT_REGUSER { get; set; }

    public Nullable<System.DateTime> PRT_REGDATE { get; set; }

    public string PRT_STATUS { get; set; }



    public virtual ap_vinculo ap_vinculo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<sass_prontuarioxavaliacao> sass_prontuarioxavaliacao { get; set; }

}

}
