
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class sass_prontuarioxavaliacao
{

    public int PRTAVC_ID { get; set; }

    public Nullable<int> PRT_ID { get; set; }

    public Nullable<int> AVC_ID { get; set; }

    public string PRTAVC_RESPOSTA { get; set; }

    public Nullable<int> PRTAVC_REGUSER { get; set; }

    public Nullable<System.DateTime> PRTAVC_REGDATE { get; set; }

    public string PRTAVC_STATUS { get; set; }



    public virtual sass_avaliacaoclinica sass_avaliacaoclinica { get; set; }

    public virtual sass_prontuario sass_prontuario { get; set; }

}

}
