
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class sass_avaliacaoclinica
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public sass_avaliacaoclinica()
    {

        this.sass_prontuarioxavaliacao = new HashSet<sass_prontuarioxavaliacao>();

    }


    public int AVC_ID { get; set; }

    public string AVC_DESCRICAO { get; set; }

    public Nullable<int> AVC_REGUSER { get; set; }

    public Nullable<System.DateTime> AVC_REGDATE { get; set; }

    public string AVC_STATUS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<sass_prontuarioxavaliacao> sass_prontuarioxavaliacao { get; set; }

}

}
