
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class sass_consulta
{

    public int CON_ID { get; set; }

    public Nullable<System.DateTime> CON_DATA { get; set; }

    public Nullable<int> CON_FUMA { get; set; }

    public Nullable<int> CON_ETILISMO { get; set; }

    public Nullable<int> CON_SEDENTARISMO { get; set; }

    public Nullable<int> CON_HIPERTENSO { get; set; }

    public Nullable<int> CON_DIABETICO { get; set; }

    public string CON_OBSERVACAO { get; set; }

    public Nullable<double> CON_PESO { get; set; }

    public Nullable<double> CON_ALTURA { get; set; }

    public Nullable<double> CON_IMC { get; set; }

    public Nullable<double> CON_PRESSAOARTERIALMAX { get; set; }

    public Nullable<double> CON_PRESSAOARTERIALMIN { get; set; }

    public Nullable<double> CON_GLICEMIA { get; set; }

    public Nullable<double> CON_COLESTEROLTOTAL { get; set; }

    public Nullable<double> CON_TRIGLICERIDEOS { get; set; }

    public Nullable<double> CON_HDL { get; set; }

    public Nullable<double> CON_LDL { get; set; }

    public Nullable<double> CON_ACIDOURICO { get; set; }

    public Nullable<int> CON_CIRCUNFERENCIAABDOMINAL { get; set; }

    public Nullable<int> CON_TIPO { get; set; }

    public Nullable<int> CON_RESPATENDIMENTO { get; set; }

    public Nullable<System.DateTime> CON_REGDATE { get; set; }

    public Nullable<int> CON_REGUSER { get; set; }

    public string CON_STATUS { get; set; }

    public Nullable<int> FUN_ID { get; set; }

    public Nullable<double> CON_ANTIHBS { get; set; }



    public virtual ap_funcionario ap_funcionario { get; set; }

}

}
