
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class systemuser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public systemuser()
    {

        this.systemuserxroles = new HashSet<systemuserxroles>();

    }


    public int SUSR_ID { get; set; }

    public string SUSR_NAME { get; set; }

    public string SUSR_LOGIN { get; set; }

    public string SUSR_PASSWORD { get; set; }

    public Nullable<int> SUSR_ROLES { get; set; }

    public Nullable<System.DateTime> SUSR_REGDATE { get; set; }

    public Nullable<int> SUSR_REGUSER { get; set; }

    public string SUSR_STATUS { get; set; }

    public string SUSR_REGUSR { get; set; }

    public Nullable<int> matricula { get; set; }

    public string SUSR_TREINAMENTO { get; set; }

    public string SUSR_PSS { get; set; }

    public string SUSR_RC { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<systemuserxroles> systemuserxroles { get; set; }

}

}
