
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class systemuser_old
{

    public int SUSR_ID { get; set; }

    public string SUSR_NAME { get; set; }

    public string SUSR_LOGIN { get; set; }

    public string SUSR_PASSWORD { get; set; }

    public Nullable<int> SUSR_ROLES { get; set; }

    public Nullable<System.DateTime> SUSR_REGDATE { get; set; }

    public Nullable<int> SUSR_REGUSER { get; set; }

    public string SUSR_STATUS { get; set; }

}

}
