
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCM.Projects.SisGeapeWeb2.Repository.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class systemuserxroles
{

    public int SUROL_ID { get; set; }

    public Nullable<int> SUSR_ID { get; set; }

    public Nullable<int> ROL_ID { get; set; }

    public Nullable<System.DateTime> SUROL_REGDATE { get; set; }

    public Nullable<int> SUROL_REGUSER { get; set; }

    public string SUROL_STATUS { get; set; }

    public Nullable<int> SIS_ID { get; set; }



    public virtual roles roles { get; set; }

    public virtual systemuser systemuser { get; set; }

}

}
